# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0002_auto_20170416_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
