# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0003_auto_20170416_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Torrent_size', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_list.Movie')),
            ],
        ),
    ]
