# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0005_auto_20170417_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='russian_movie_title',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='year',
        ),
        migrations.AddField(
            model_name='torrent',
            name='link_to_topic',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='torrent',
            name='link_to_torrent_download',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='torrent',
            name='subtitles',
            field=models.BooleanField(default=False),
        ),
    ]
