# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0006_auto_20170417_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default=''),
        ),
    ]
