# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0007_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='testrate',
            field=models.FloatField(default=0),
        ),
    ]
