# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0008_movie_testrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='testrate',
        ),
        migrations.AddField(
            model_name='movie',
            name='names',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AddField(
            model_name='torrent',
            name='torrent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torrent',
            name='tracker',
            field=models.CharField(default='', max_length=200),
        ),
    ]
